### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by idontgetoutmuch** [cdepillabout/nix-reverse-deps-of-haskell-package#2]
This tool looks really useful but I am not clear how to use it.

I make my change to package `random`:
```
   random =nixpkgs.haskellPackages.callCabal2nix "random" (builtins.fetchGit {
    url = "https://github.com/idontgetoutmuch/random.git";
    rev = "4bb37cfd588996c55e62ec4f908b8ea7d99a38f6";
    ref = "interface-to-performance";
  }) { };
```
But `nixpkgs` doesn't know about this. It only knows `pkgs/development/haskell-modules/hackage-packages.nix` which contains
```
  "random" = callPackage
    ({ mkDerivation, base, time }:
     mkDerivation {
       pname = "random";
       version = "1.1";
       sha256 = "0nis3lbkp8vfx8pkr6v7b7kr5m334bzb0fk9vxqklnp2aw8a865p";
       revision = "1";
       editedCabalFile = "1pv5d7bm2rgap7llp5vjsplrg048gvf0226y0v19gpvdsx7n4rvv";
       libraryHaskellDepends = [ base time ];
       testHaskellDepends = [ base ];
       description = "random number library";
       license = stdenv.lib.licenses.bsd3;
     }) {};
```
So what do I have to do to make my changed package visible? Do I have to recreate `hackage-packages.nix` (which seems non-trivial)?

**Comment by cdepillabout** [comment]
In #4 I added an example of how to use this when overriding a package.  I tested this locally, and it seemed to work.

You may have to adapt the example slightly for what you want to do, but it should hopefully give you a good starting point.
